# Generated by Django 2.1.8 on 2019-06-02 09:33

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outstation', '0002_auto_20190602_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onroutetouristplaces',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_route_places', to='outstation.OutstationRoutePage', unique=True),
        ),
    ]
