# Generated by Django 2.1.8 on 2019-06-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='duration_of_visit',
            field=models.DurationField(max_length=100),
        ),
    ]
